services:
  postgres-test:
    image: postgres:15
    ports:
      - "5433:5432"   # avoid clashing with dev Postgres on 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: testdb
    container_name: db-test